management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
      

resilience4j:
  circuitbreaker:
    instances:
      serviceUser:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
    
  retry:
    instances:
      serviceUser:
        maxRetryAttempts: 5
        waitDuration: 10s
        
  ratelimiter:
    instances:
      serviceUser:
        registerHealthIndicator: false
        limitForPeriod: 10
        limitRefreshPeriod: 12s
        timeoutDuration: 3s
        
        